config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/about'
  resources :sentences, only: [:new, :create, :show]
  root 'sentences#new'
  get '/download_pdf/:id(.:format)' => 'sentences#show', :method => :get, :as=>:show

  resources :contacts, only: [:new, :create]
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name, 		:validate => true
	attribute :email, 		:validate => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/
	attribute :message,		:validate => true
	
	
 	def your_email(email)	
	    {to: email, from: "ja180@vp.pl", subject: 'Welcome to My Awesome Site'}
	end

	def headers 
		{
			:subject => "Contact Form",
			:to => "ja180@vp.pl",
			:from => %("#{name}" <#{email}>)
		}
	end
end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  validates :title, presence: true, length: { maximum: 200 }
  validates :body, presence: true, length: { maximum: 100000 }

  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
  class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if verify_recaptcha(:contact => @contact) && @contact.deliver
			flash[:success]= "Thanks for your message! I'll get back to you soon!"
			redirect_to root_path
		else 
			flash.now[:error]= "Cannot send message"
			render :new
		end
	end
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  def new
    @sentences = Sentence.delete_all
  	@sentence = Sentence.new
  end

  def create
  	@sentence = Sentence.new(sentence_params)
  	if @sentence.save
  		redirect_to @sentence
  	else
  		render 'new', notice: "Your text wasn't added"
  	end
  end

  def show
    stop_words = %w[a able about above abst accordance according accordingly
                 across act actually added adj affected affecting affects after
                 afterwards again against ah all almost alone along already also 
                 although always am among amongst an and announce another any 
                 anybody anyhow anymore anyone anything anyway anyways 
                 anywhere apparently approximately are aren arent arise around 
                 as aside ask asking at auth available away awfully b back be became 
                 because become becomes becoming been before beforehand begin beginning 
                 beginnings begins behind being believe below beside besides between beyond 
                 biol both brief briefly but by c ca came can cannot can't cause causes 
                 certain certainly co com come comes contain containing contains could couldnt 
                 d date did didn't different do does doesn't doing done don't down downwards due 
                 during e each ed edu effect eg eight eighty either else elsewhere end ending 
                 enough especially et et-al etc even ever every everybody everyone everything 
                 everywhere ex except f far few ff fifth first five fix followed following follows 
                 for former formerly forth found four from further furthermore g gave get gets getting 
                 give given gives giving go goes gone got gotten h had happens hardly has hasn't have 
                 haven't having he hed hence her here hereafter hereby herein heres hereupon hers 
                 herself hes hi hid him himself his hither home how howbeit however hundred i 
                 id ie if i'll im immediate immediately importance important in inc indeed index 
                 information instead into invention inward is isn't it itd it'll its itself i've 
                 j just k keep  keeps kept kg km know known knows l largely last lately later latter 
                 latterly least less lest let lets like liked likely line little 'll look looking 
                 looks ltd m made mainly make makes many may maybe me mean means meantime meanwhile 
                 merely mg might million miss ml more moreover most mostly mr mrs much mug must my 
                 myself n na name namely nay nd near nearly necessarily necessary need needs neither 
                 never nevertheless new next nine ninety no nobody non none nonetheless noone nor 
                 normally nos not noted nothing now nowhere o obtain obtained obviously of off 
                 often oh ok okay old omitted on once one ones only onto or ord other others 
                 otherwise ought our ours ourselves out outside over overall owing own p page 
                 pages part particular particularly past per perhaps placed please plus poorly possible 
                 possibly potentially pp predominantly present previously primarily probably promptly 
                 proud provides put q que quickly quite qv r ran rather rd re readily really recent 
                 recently ref refs regarding regardless regards related relatively research respectively 
                 resulted resulting results right run s said same saw say saying says sec section see 
                 seeing seem seemed seeming seems seen self selves sent seven several shall she shed 
                 she'll shes should shouldn't show showed shown showns shows significant significantly 
                 similar similarly since six slightly so some somebody somehow someone somethan something 
                 sometime sometimes somewhat somewhere soon sorry specifically specified specify specifying 
                 still stop strongly sub substantially successfully such sufficiently suggest sup sure to the]

  	@sentence = Sentence.friendly.find(params[:id])
    @txt = @sentence.body
    arr = []
    arr << @txt.downcase
    text = arr.join
    @words = text.split(/[^a-zA-Z]/)
    # zliczenie znaków
    @character_count = text.length
    @character_count_nospaces = text.gsub(/[^a-zA-Z']/, '').length

    # zliczenie s³ów, zdañ i akapitów
    @word_count = text.split.length
    @sentence_count = text.split(/\.|\?|!/).length
    @paragraph_count = text.split(/\n\n/).length

    # utworzenie listy s³ów z tekstu, które nie s¹ s³owami pomijanymi
    # zliczenie tych s³ów i wyznaczenie procentowej iloœci s³ów pomijanych
    # w zbiorze wszystkich s³ów
    all_words = text.scan(/\w+/)
    good_words = all_words.select{ |word| !stop_words.include?(word) }
    @good_percentage = ((good_words.length.to_f / all_words.length.to_f) * 100).to_i

    # podsumowanie - wyodrêbnienie zdañ potencjalnie najbardziej znacz¹cych
    sentences = text.gsub(/\s+/, ' ').strip.split(/\.|\?|\!/)
    sentences_sorted = sentences.sort_by { |sentence| sentence.length }
    one_third = sentences_sorted.length / 5
    @ideal_sentences = sentences_sorted.slice(one_third, one_third + 1)
    @ideal_sentences = @ideal_sentences.select { |sentence| sentence =~ /is|are/ }
    @ideal_sentences = @ideal_sentences.to_s.gsub(/[^a-zA-Z,.]/, ' ')
    @bad_percentage = 100 - @good_percentage

    @freqs = Hash.new(0)
    @words.each do |word|  
      if !stop_words.include?(word) 
        @freqs[word] += 1 
      end
    end
    @freqs = @freqs.sort_by {|x,y| y }
    @freqs.reverse!
    @freqs = @freqs[1..11]

    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "show", javascript_delay: 7000, :layout => 'pdf.html.erb',:template => '/sentences/show'  # Excluding ".pdf" extension.
      end
    end
  end

  private

  def sentence_params 
  	params.require(:sentence).permit(:title, :body)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def set_title_of_page(page_title="")
		add = "Count text"
		if page_title.empty?
			page_title = add
		else
			page_title = add+": "+page_title
		end
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/sentences/show.html.erb
<% provide(:title, @sentence.title) %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<div class="container-fluid">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-body">

        <div class="col-md-3">
          <%= link_to image_tag('logo3.png'), root_path %>
        </div> 

        <div class="col-md-9">
         <h3><%= @sentence.title %></h3>
         <br>
        </div>

        <div class="col-md-12">
        </div>
        <div class="col-md-6">
        <div class="panel panel-default">
         <div class="panel-body">
          <table class="table table-striped table-hover ">
            <thead>
              <tr>
                <th><h4>Statistic:</h4></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>All characters:</td>
                <td><%= @character_count %></td>
              </tr>
              <tr>
                <td>Characters without spaces:</td>
                <td><%= @character_count_nospaces %></td>
              </tr>
              <tr>
                <td>Words: </td>
                <td><%= @word_count %></td>
              </tr>
              <tr>
                <td>Sentence:</td>
                <td><%= @sentence_count %></td>
              </tr>
              <tr>
                <td>Average characters in one word:</td>
                <td><%= (@character_count_nospaces.to_f/@word_count).round(2) %></td>
              </tr>
              <tr>
                <td>Average words in one sentence:</td>
                <td><%= (@word_count.to_f/@sentence_count).round(2) %> </td>
              </tr>
              <tr>
                <td>Percente good words:</td>
                <td><%= @good_percentage %>%</td>
              </tr>
            </tbody>
          </table>
        </div>
        </div>
        </div>

        <div class="col-md-6">
          <%= raw pie_chart ({"Good words" => @good_percentage, "Stop words" => @bad_percentage}) %>
        </div>
        

        <div class="col-md-12">
         <div class="panel panel-default">
         <div class="panel-body">
          <table class="table table-striped table-hover ">
          <h4>Top unfiltered words: </h4>
            <thead>
              <tr>
                <th>Word</th>
                <th>Amount </th>
                <th>Percent </th>
              </tr>
            </thead>
            <tbody>
             <% @freqs.each do |word, freq| %>
              <tr>
                <td><%= word %> </td>
                <td><%=freq.to_s %> </td>
                <td><%=((freq.to_f/@character_count_nospaces)*100).round(2) %> %</td>
              </tr>
          <% end %>
           </tbody>
          </table>
          </div>
          </div>
        </div>

        <div class="col-md-12">
          <%= column_chart (@freqs.each { |word, freq| {"#{word}" => freq} })%>
        </div>

        <div class="col-md-12">
          <div class="panel panel-default">
             <div class="panel-body">
              <h4>Summary sentences:</h4>
             </div>
              <div class="panel-footer">
                 <blockquote><%= @ideal_sentences %></blockquote>
              </div>
            </div>
        </div>

        <div class="col-md-12">
           <p style="text-align:center">
            <%= link_to new_sentence_path, class: "btn btn-primary" do %><span class="glyphicon glyphicon-chevron-left"></span> Back<% end %>
            <%= link_to show_path(@sentence, :format => :pdf), class: "btn btn-success" do%><span class="glyphicon glyphicon-print"></span> PDF <% end %>
           </p>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<br>
<br>
 

app/views/sentences/show.pdf.erb
        <div class="col-md-3">
          <h2>Title: <%= @sentence.title %> - statistisc from www.counttxt.com</h2>
        </div> 

        <div class="col-md-12">
        </div>
        <div class="col-md-12">
          <table class="table table-striped table-hover ">
            <thead>
              <tr>
                <th><h4>Statistic:</h4></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>All characters:</td>
                <td><%= @character_count %></td>
              </tr>
              <tr>
                <td>Characters without spaces:</td>
                <td><%= @character_count_nospaces %></td>
              </tr>
              <tr>
                <td>Words: </td>
                <td><%= @word_count %></td>
              </tr>
              <tr>
                <td>Sentence:</td>
                <td><%= @sentence_count %></td>
              </tr>
              <tr>
                <td>Average characters in one word:</td>
                <td><%= (@character_count_nospaces.to_f/@word_count).round(2) %></td>
              </tr>
              <tr>
                <td>Average words in one sentence:</td>
                <td><%= (@word_count.to_f/@sentence_count).round(2) %> </td>
              </tr>
              <tr>
                <td>Percente good words:</td>
                <td><%= @good_percentage %>%</td>
              </tr>
            </tbody>
          </table>
        </div>
        

        <div class="col-md-12">
          <table class="table table-striped table-hover ">
          <h4>Top unfiltered words: </h4>
            <thead>
              <tr>
                <th>Word</th>
                <th>Amount </th>
                <th>Percent </th>
              </tr>
            </thead>
            <tbody>
             <% @freqs.each do |word, freq| %>
              <tr>
                <td><%= word %> </td>
                <td><%=freq.to_s %> </td>
                <td><%=((freq.to_f/@character_count_nospaces)*100).round(2) %> %</td>
              </tr>
          <% end %>
           </tbody>
          </table>
        </div>

        <div class="col-md-12">
          <h4>Summary sentences:</h4>
          <blockquote><%= @ideal_sentences %></blockquote>
        </div>
      